const translations = {
  en: {
    login: "LOGIN",
    register: "REGISTER",
    password: "Password",
    liveChat: "LIVE CHAT",
    selectLanguage: "English",
    sport: "SPORT",
    todaysBet: "TODAY'S BET",
    live: "LIVE",
    jackpot: "JACKPOT",
    virtual: "VIRTUAL",
    specialGames: "SPECIAL GAMES",
    crashGames: "CRASH GAMES",
    race: "RACE",
    promo: "PROMO",
    sportsMenu: "Sports Menu",
    searchEvent: "Search Event",
    searchPlaceholder: "Insert event name or team...",
    quickFilter: "Quick Filter",
    inPlay: "In-Play",
    sports: "Sports",
    esports: "Esports",
    showMore: "Show more",
    football: "Football",
    basketball: "Basketball",
    tennis: "Tennis",
    iceHockey: "Ice Hockey",
    volleyball: "Volleyball",
    rugbyUnion: "Rugby Union",
    tableTennis: "Table Tennis",
    rugbyLeague: "Rugby League",
    leagueOfLegends: "League of Legends",
    counterStrike: "Counter-Strike: GO",
    rainbowSix: "Rainbow Six",
    callOfDuty: "Call of Duty",
    dota2: "Dota 2",
    topMatches: "Top Matches",
    matchResult: "Match Result",
    noBets: "No bets added yet",
    single: "SINGLE",
    stake: "Stake",
    taxes: "Taxes",
    oddsType: "Odds Type",
    adjustments: "Adjustments",
    loginToBet: "You need to login to be able to place a bet.",
    setStake: "Set stake to place a bet!",
    share: "Share",
    cancel: "CANCEL",
    placeBet: "PLACE BET",
    betslip: "Betslip",
    premierLeague: "Premier League",
  },
  am: {
    login: "ይግቡ",
    register: "ለመመዝገብ",
    password: "የይለፍ ቃል",
    liveChat: "ቀጥታ ውይይት",
    selectLanguage: "አማርኛ",
    sport: "ስፖርት",
    todaysBet: "የዛሬ ውርርድ",
    live: "ቀጥታ",
    jackpot: "ጃክፖት",
    virtual: "ምንም ያልሆነ ጨዋታ",
    specialGames: "ልዩ ጨዋታዎች",
    crashGames: "ክራሽ ጨዋታዎች",
    race: "ውድድር",
    promo: "ማስተዋወቅ",
    sportsMenu: "የስፖርት ምናሌ",
    searchEvent: "ክስተት ፈልግ",
    searchPlaceholder: "የዝርዝሩን ስም ወይም ቡድን አስገባ...",
    quickFilter: "ፈጣን ማጣሪያ",
    inPlay: "በስፖርት ላይ",
    sports: "ስፖርት",
    esports: "ኢስፖርት",
    showMore: "ተጨማሪ አሳይ",
    football: "እግር ኳስ",
    basketball: "ተሽከርካሪ ኳስ",
    tennis: "ቴኒስ",
    iceHockey: "አይስ ሆኪ",
    topMatches: "ከፍተኛ ውርደት",
    matchResult: "ውጤት መጠን",
    betslip: "የውርደት ቅድመምሕረት",
    premierLeague: "ፕሪምየር ሊግ",

    noBets: "ምንም ውርደት አልተጨመረም",
    single: "ነጠላ",
    stake: "የውርደት መጠን",
    taxes: "ግብር",
    oddsType: "የውርደት አይነት",
    adjustments: "ማስተካከያዎች",
    loginToBet: "ውርደት ለማድረግ መግባት ያስፈልጋል።",
    setStake: "ውርደት ለማድረግ መጠን ይሰይሩ!",
    share: "እኩል አድርግ",
    cancel: "ሰርዝ",
    placeBet: "ውርደት አድርግ",
  },
  or: {
    login: "Galii",
    register: "Galmaa'i",
    password: "Jecha icciti",
    liveChat: "Waliigaltee Jireenya",
    selectLanguage: "Oromiffa",
    sport: "Ispoortii",
    todaysBet: "Filannoo har'a",
    live: "Sirna Gaba",
    jackpot: "Jackpotii",
    virtual: "Tapha Muddamuu",
    specialGames: "Tapha Addaa",
    crashGames: "Tapha Muraa",
    race: "Gorsa",
    promo: "Beeksisa",
    sportsMenu: "Maaloo Isportii",
    searchEvent: "Tapha barbaadi",
    quickFilter: "Filannoo saffisaa",
    inPlay: "Tapha keessa",
    sports: "Isportii",
    esports: "Esportii",
    showMore: "Caalatti mul'isi",
    football: "Kubbaa miilaa",
    basketball: "Kubbaa gaggabaa",
    topMatches: "Tapha Gurguddoo",
    matchResult: "Bu'aa Taphaa",
    betslip: "Fula Filannoo",

    premierLeague: "Ligii Ingiliizii",
    noBets: "Filannoon hin jiraatin",
    single: "Tokkee",
    stake: "Gatii",
    taxes: "Taaksii",
    oddsType: "Gatii Filannoo",
    adjustments: "Gareewwan",
    loginToBet: "Tapha filachuuf seena argachuu qabda.",
    setStake: "Gatii taphaa filadhu!",
    share: "Qoodi",
    cancel: "Haquu",
    placeBet: "Filadhu",
  },
};

export type Language = keyof typeof translations;
export type TranslationKeys = keyof (typeof translations)["en"];

export default translations;
